./compile -l -a -v ../tests/PERIOD_EXPECTED.in > ../tests/PERIOD_EXPECTED.out
./compile -l -a -v ../tests/IDENTIFIER_EXPECTED_CONST_DECLARATION.in > ../tests/IDENTIFIER_EXPECTED_CONST_DECLARATION.out
./compile -l -a -v ../tests/EQUALS_EXPECTED_CONST_DECLARATION.in > ../tests/EQUALS_EXPECTED_CONST_DECLARATION.out
./compile -l -a -v ../tests/NUMBER_EXPECTED_CONST_DECLARATION.in > ../tests/NUMBER_EXPECTED_CONST_DECLARATION.out
./compile -l -a -v ../tests/SEMICOLON_EXPECTED_CONST_DECLARATION.in > ../tests/SEMICOLON_EXPECTED_CONST_DECLARATION.out
./compile -l -a -v ../tests/IDENTIFIER_EXPECTED_VAR_DECLARATION.in > ../tests/IDENTIFIER_EXPECTED_VAR_DECLARATION.out
./compile -l -a -v ../tests/SEMICOLON_EXPECTED_VAR_DECLARATION.in > ../tests/SEMICOLON_EXPECTED_VAR_DECLARATION.out
./compile -l -a -v ../tests/BECOMES_EXPECTED_ASSIGNMENT_STATEMENT.in > ../tests/BECOMES_EXPECTED_ASSIGNMENT_STATEMENT.out
./compile -l -a -v ../tests/END_EXPECTED_BEGIN_STATEMENT.in > ../tests/END_EXPECTED_BEGIN_STATEMENT.out
./compile -l -a -v ../tests/THEN_EXPECTED_IF_STATEMENT.in > ../tests/THEN_EXPECTED_IF_STATEMENT.out
./compile -l -a -v ../tests/DO_EXPECTED_WHILE_STATEMENT.in > ../tests/DO_EXPECTED_WHILE_STATEMENT.out
./compile -l -a -v ../tests/IDENTIFIER_EXPECTED_READ_STATEMENT.in > ../tests/IDENTIFIER_EXPECTED_READ_STATEMENT.out
./compile -l -a -v ../tests/IDENTIFIER_EXPECTED_WRITE_STATEMENT.in > ../tests/IDENTIFIER_EXPECTED_WRITE_STATEMENT.out
./compile -l -a -v ../tests/REL_OP_EXPECTED.in > ../tests/REL_OP_EXPECTED.out
./compile -l -a -v ../tests/INVALID_EXPRESSION.in > ../tests/INVALID_EXPRESSION.out
./compile -l -a -v ../tests/RIGHT_PARENTHESIS_EXPECTED_FACTOR.in > ../tests/RIGHT_PARENTHESIS_EXPECTED_FACTOR.out
./compile -l -a -v ../tests/EXCEEDED_MAX_CODE_LENGTH.in > ../tests/EXCEEDED_MAX_CODE_LENGTH.out
./compile -l -a -v ../tests/UNDECLARED_IDENTIFIER.in > ../tests/UNDECLARED_IDENTIFIER.out
./compile -l -a -v ../tests/ASSIGNMENT_TO_NON_VARIABLE.in > ../tests/ASSIGNMENT_TO_NON_VARIABLE.out
./compile -l -a -v ../tests/READ_INTO_INVALID_IDENTIFIER.in > ../tests/READ_INTO_INVALID_IDENTIFIER.out
./compile -l -a -v ../tests/READ_INTO_NON_VARIABLE.in > ../tests/READ_INTO_NON_VARIABLE.out
./compile -l -a -v ../tests/WRITE_FROM_INVALID_IDENTIFIER.in > ../tests/WRITE_FROM_INVALID_IDENTIFIER.out
./compile -l -a -v ../tests/IDENTIFIER_ALREADY_DECLARED.in > ../tests/IDENTIFIER_ALREADY_DECLARED.out