./compile -l -a -v ../tests/in/sample.in > ../tests/out/sample.out
./compile -l -a -v ../tests/in/UNEXPECTED_END_OF_PROGRAM.in > ../tests/out/UNEXPECTED_END_OF_PROGRAM.out
./compile -l -a -v ../tests/in/IDENTIFIER_EXPECTED_CONST_DECLARATION.in > ../tests/out/IDENTIFIER_EXPECTED_CONST_DECLARATION.out
./compile -l -a -v ../tests/in/EQUALS_EXPECTED_CONST_DECLARATION.in > ../tests/out/EQUALS_EXPECTED_CONST_DECLARATION.out
./compile -l -a -v ../tests/in/NUMBER_EXPECTED_CONST_DECLARATION.in > ../tests/out/NUMBER_EXPECTED_CONST_DECLARATION.out
./compile -l -a -v ../tests/in/SEMICOLON_EXPECTED_CONST_DECLARATION.in > ../tests/out/SEMICOLON_EXPECTED_CONST_DECLARATION.out
./compile -l -a -v ../tests/in/IDENTIFIER_EXPECTED_VAR_DECLARATION.in > ../tests/out/IDENTIFIER_EXPECTED_VAR_DECLARATION.out
./compile -l -a -v ../tests/in/SEMICOLON_EXPECTED_VAR_DECLARATION.in > ../tests/out/SEMICOLON_EXPECTED_VAR_DECLARATION.out
./compile -l -a -v ../tests/in/BECOMES_EXPECTED_ASSIGNMENT_STATEMENT.in > ../tests/out/BECOMES_EXPECTED_ASSIGNMENT_STATEMENT.out
./compile -l -a -v ../tests/in/END_EXPECTED_BEGIN_STATEMENT.in > ../tests/out/END_EXPECTED_BEGIN_STATEMENT.out
./compile -l -a -v ../tests/in/THEN_EXPECTED_IF_STATEMENT.in > ../tests/out/THEN_EXPECTED_IF_STATEMENT.out
./compile -l -a -v ../tests/in/DO_EXPECTED_WHILE_STATEMENT.in > ../tests/out/DO_EXPECTED_WHILE_STATEMENT.out
./compile -l -a -v ../tests/in/IDENTIFIER_EXPECTED_READ_STATEMENT.in > ../tests/out/IDENTIFIER_EXPECTED_READ_STATEMENT.out
./compile -l -a -v ../tests/in/IDENTIFIER_EXPECTED_WRITE_STATEMENT.in > ../tests/out/IDENTIFIER_EXPECTED_WRITE_STATEMENT.out
./compile -l -a -v ../tests/in/REL_OP_EXPECTED.in > ../tests/out/REL_OP_EXPECTED.out
./compile -l -a -v ../tests/in/INVALID_EXPRESSION.in > ../tests/out/INVALID_EXPRESSION.out
./compile -l -a -v ../tests/in/RIGHT_PARENTHESIS_EXPECTED_FACTOR.in > ../tests/out/RIGHT_PARENTHESIS_EXPECTED_FACTOR.out
./compile -l -a -v ../tests/in/EXCEEDED_MAX_CODE_LENGTH.in > ../tests/out/EXCEEDED_MAX_CODE_LENGTH.out
./compile -l -a -v ../tests/in/UNDECLARED_IDENTIFIER.in > ../tests/out/UNDECLARED_IDENTIFIER.out
./compile -l -a -v ../tests/in/ASSIGNMENT_TO_NON_VARIABLE.in > ../tests/out/ASSIGNMENT_TO_NON_VARIABLE.out
./compile -l -a -v ../tests/in/READ_INTO_INVALID_IDENTIFIER.in > ../tests/out/READ_INTO_INVALID_IDENTIFIER.out
./compile -l -a -v ../tests/in/READ_INTO_NON_VARIABLE.in > ../tests/out/READ_INTO_NON_VARIABLE.out
./compile -l -a -v ../tests/in/WRITE_FROM_INVALID_IDENTIFIER.in > ../tests/out/WRITE_FROM_INVALID_IDENTIFIER.out
./compile -l -a -v ../tests/in/IDENTIFIER_ALREADY_DECLARED.in > ../tests/out/IDENTIFIER_ALREADY_DECLARED.out